[package]
name = "light-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wallet = { path = "./wallet" }

yew = { version = "0.21.0", features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.2"
web-sys = "0.3.66"
js-sys = "0.3.66"
wasm-logger = "0.2.0"
wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4.39"
yew-router = "0.18.0"
log = "0.4.20"

[workspace]
members = ["src-tauri"]
