[package]
name = "wallet"
version.workspace = true
edition.workspace = true

[dependencies]
bip32.workspace = true
serde.workspace = true
serde_json.workspace = true
rand_core.workspace = true
toml.workspace = true

util = { path = "../util" }