[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
bip32 = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand_core = { version = "0.6.4", features = ["std"] }
toml = "0.8.8"
util = { path = "../util" }