name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Wasm
      run: rustup target add wasm32-unknown-unknown
    - name: Install Tauri cli
      run: cargo install tauri-cli
    - name: Build
      run: cargo tauri build
    - name: Run tests
      run: cargo test --verbose
